name: building, linting, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      [ master ]
  pull_request:
    branches:
      [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
      - name: Building production bundle
        run: npm run build:production
      - name: Linting TypeScript
        run: npm lint:ts
      - name: Linting scss
        run: npm lint:scss
      - name: Testing UI
        run: npm run test
